import Header from '@/components/header/Header' // Adjust the path based on your setup
import Footer from '@/components/footer/Footer'; 
import ServicesBar from '@/components/top-services-bar/ServicesBar';// Adjust the path based on your setup
import './globals.css'; // Global styles

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <ServicesBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
